[PHP]
extension_dir = "C:/laragon/bin/php/php-8.4.13/ext"

extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_gd.dll
extension=php_mbstring.dll
extension=php_openssl.dll
extension=php_pdo_mysql.dll
extension=php_sqlite3.dll
extension=php_zip.dll

memory_limit=512M
upload_max_filesize=100M
post_max_size=100M
max_execution_time=300
date.timezone=UTC
